import { PlanConfig, PermissionPolicy } from '@/types/domain';

export const BAMBOOKIT_PLANS: PlanConfig[] = [
  {
    id: 'free',
    name: 'Free',
    priceInr: 0,
    interval: 'month',
    headline: 'For independent developers exploring autonomous agent workflows.',
    description: 'Local execution control with full BYOK support and basic observability.',
    features: [
      'Up to 2 active projects',
      'Local agent execution via Desktop Connector',
      'Basic agent session control & terminal stream',
      'Full BYOK (OpenAI, Anthropic, Gemini, Local)',
      '14-day agent session history',
      'Standard permission gates & manual approvals',
      'Community support',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    priceInr: 799,
    interval: 'month',
    headline: 'For professional software engineers shipping production apps.',
    description: 'Cloud execution, phone control, persistent worker environments, and replay.',
    isPopular: true,
    features: [
      'Unlimited local & cloud projects',
      'Cloud worker execution with isolated environments',
      'Full Android phone control & mobile notifications',
      'Interactive Agent Replay & deep diff inspector',
      'Granular permission policies (Files, Net, Exec, Git)',
      'Per-task & per-agent budget firewall limits',
      'Automatic deployment triggers & test gates',
      '90-day searchable agent audit log',
      'Priority email support',
    ],
  },
  {
    id: 'team',
    name: 'Team',
    priceInr: 2499,
    interval: 'month',
    headline: 'For engineering teams coordinating multi-agent workflows.',
    description: 'Collaborative workspaces, shared agent sessions, roles, and compliance.',
    features: [
      'Includes 5 team members (add seats flexibly)',
      'Shared team projects & centralized BYOK keys',
      'Multi-agent orchestration & conflict prevention',
      'Role-based access control (Admin, Dev, Viewer)',
      'Approval escalation rules (e.g. 2-person production gates)',
      'Immutable audit events stream',
      'Unlimited agent session history',
      'Dedicated Slack/Discord support channel',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    priceInr: 0, // Custom
    interval: 'month',
    headline: 'For organizations with custom security and compliance needs.',
    description: 'Self-hosted workers, private VPC connectivity, SSO, and SLA guarantees.',
    features: [
      'Self-hosted worker nodes in your own AWS/GCP/Azure VPC',
      'SAML SSO, Okta, and SCIM provisioning',
      'Custom air-gapped agent runtime support',
      'Custom data retention & compliance policies (SOC2, HIPAA)',
      'Custom SLA & 24/7 dedicated engineering support',
      'Custom invoice & procurement terms',
    ],
  },
];

export const DEFAULT_PERMISSIONS: PermissionPolicy[] = [
  {
    category: 'filesystem',
    name: 'Filesystem Access',
    description: 'Read and write permissions within the project workspace tree.',
    state: 'allowed',
    customRules: ['Restricted to project root', 'Excludes .env files by default'],
  },
  {
    category: 'git',
    name: 'Git Version Control',
    description: 'Create branches, commit diffs, inspect status, and create pull requests.',
    state: 'allowed',
    customRules: ['Pushing directly to main branch requires approval'],
  },
  {
    category: 'terminal',
    name: 'CLI & Package Manager',
    description: 'Execute npm/pnpm/yarn, run test suites, and build scripts.',
    state: 'allowed',
  },
  {
    category: 'network',
    name: 'Outbound Network Access',
    description: 'Ability to fetch packages and external documentation APIs.',
    state: 'allowed',
  },
  {
    category: 'secrets',
    name: 'Environment Secrets',
    description: 'Reading production or staging secrets and tokens.',
    state: 'approval_required',
    customRules: ['Masked in logs', 'Never streamed to external LLM directly'],
  },
  {
    category: 'database',
    name: 'Database Migrations & Schemas',
    description: 'Running migration scripts and altering database schemas.',
    state: 'approval_required',
  },
  {
    category: 'deployment',
    name: 'Staging Deployment',
    description: 'Triggering automated previews and staging builds.',
    state: 'allowed',
  },
  {
    category: 'production',
    name: 'Production Deployment & Rollback',
    description: 'Promoting build artifacts to live production instances.',
    state: 'approval_required',
  },
  {
    category: 'cloud',
    name: 'Cloud Infrastructure Provisioning',
    description: 'Creating/deleting cloud resources like S3, ECS, or VPC endpoints.',
    state: 'blocked',
  },
];
